# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROfKHxt0mp7pg_hb2LhEsREzL8TW86Wi
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import time

# ==========================================
# 1. CONFIGURACIÓN
# ==========================================
st.set_page_config(
    page_title="ADICOM | ESG & Sostenibilidad",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded"
)

# URLs de Google Sheets (Evitando el caché)
timestamp = int(time.time())
URL_KPIS = f"https://docs.google.com/spreadsheets/d/e/2PACX-1vQklg9IQYomXAn3t9xCsQu7zDScqlO38Yrl9rNXdscrdiao7wU1u3kyWJa7IPUR8g/pub?gid=1096975805&single=true&output=csv&_nocache={timestamp}"
URL_ROADMAP = f"https://docs.google.com/spreadsheets/d/e/2PACX-1vQklg9IQYomXAn3t9xCsQu7zDScqlO38Yrl9rNXdscrdiao7wU1u3kyWJa7IPUR8g/pub?gid=2082257667&single=true&output=csv&_nocache={timestamp}"

# ==========================================
# 2. ESTILOS CSS (DISEÑO LIMPIO Y MINIMALISTA - VERDE SAGE)
# ==========================================
st.markdown("""
<style>
    .main { background-color: #F9FAFB; }
    h1, h2, h3, h4 { color: #2C3E50; font-family: 'Segoe UI', sans-serif; }
    
    /* Cuadrantes estilo tarjeta */
    .quadrant-card {
        background: white;
        border-radius: 12px;
        padding: 20px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        border-top: 4px solid #6baf84;
        height: 100%;
        margin-bottom: 20px;
    }
    
    /* Badges de Ventajas */
    .badge-adicom {
        background-color: #e8f5e9;
        color: #2e7d32;
        padding: 4px 10px;
        border-radius: 15px;
        font-size: 0.8rem;
        font-weight: bold;
        display: inline-block;
        margin-bottom: 5px;
    }
    .badge-client {
        background-color: #e3f2fd;
        color: #1565c0;
        padding: 4px 10px;
        border-radius: 15px;
        font-size: 0.8rem;
        font-weight: bold;
        display: inline-block;
        margin-bottom: 5px;
    }
    
    /* Roadmap Timeline (Bolitas) */
    .timeline-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        position: relative;
        padding: 20px 0;
    }
    .timeline-line {
        position: absolute;
        top: 50%;
        left: 5%;
        right: 5%;
        height: 2px;
        background-color: #D1D5DB;
        z-index: 1;
    }
    .timeline-node {
        width: 35px;
        height: 35px;
        background-color: white;
        border: 3px solid #6baf84;
        border-radius: 50%;
        z-index: 2;
        display: flex;
        justify-content: center;
        align-items: center;
        font-weight: bold;
        color: #2C3E50;
    }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 3. DATOS SIMULADOS PARA EL DASHBOARD
# ==========================================
certificaciones = ["ISO 14001 (Ambiental)", "ISO 45001 (SST)", "ISO 9001 (Calidad)"]

datos_certificacion = {
    "ISO 14001 (Ambiental)": {
        "que_es": "El Sistema de Gestión Ambiental (EMS) permite gestionar el impacto ecológico de la empresa, garantizar el cumplimiento legal y fomentar la mejora continua.",
        "ventajas_adicom": [
            ("Diferenciación Comercial", "Puntaje extra en licitaciones y concursos."),
            ("Eficiencia Operativa", "Reducción en consumo de energía y residuos.")
        ],
        "ventajas_clientes": [
            ("Cumplimiento y Sostenibilidad", "Ayuda a las metas ESG del cliente (ej. Ternium, Weir)."),
            ("Menor Riesgo", "Cadena de suministro blindada ante multas ambientales.")
        ],
        "kpis": {"Inv Inicial": "$15,000", "ROI Esperado": "22%", "Costo Mensual": "$1,200"}
    }
}

# ==========================================
# 4. INTERFAZ DE USUARIO (CUADRANTES)
# ==========================================
st.sidebar.image("https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=300&q=80", caption="ADICOM Sostenible")
st.sidebar.title("Menú Principal")

menu_opcion = st.sidebar.radio("Navegación:", ["Dashboard de Certificaciones", "Tabla Interactiva / Checklist global"])

if menu_opcion == "Dashboard de Certificaciones":
    cert_sel = st.sidebar.selectbox("Selecciona una Certificación:", certificaciones)
    
    st.title(f"📊 Panel Estratégico: {cert_sel}")
    
    # Cuadrantes Superiores
    col1, col2 = st.columns(2)
    
    # Cuadrante 1: ¿Qué es?
    with col1:
        st.markdown(f"""
        <div class="quadrant-card">
            <h3 style="color: #6baf84;">¿Qué es?</h3>
            <p style="font-size: 1.1rem; color: #4b5563;">
                {datos_certificacion.get(cert_sel, datos_certificacion["ISO 14001 (Ambiental)"])["que_es"]}
            </p>
        </div>
        """, unsafe_allow_html=True)
        
    # Cuadrante 2: Roadmap (Línea de tiempo con bolitas)
    with col2:
        st.markdown('<div class="quadrant-card">', unsafe_allow_html=True)
        st.markdown('<h3 style="color: #6baf84;">Roadmap (Milestones)</h3>', unsafe_allow_html=True)
        
        # Simulación visual del roadmap
        st.markdown("""
        <div class="timeline-container">
            <div class="timeline-line"></div>
            <div class="timeline-node" style="background-color: #6baf84; color: white;">1</div>
            <div class="timeline-node" style="background-color: #6baf84; color: white;">2</div>
            <div class="timeline-node">3</div>
            <div class="timeline-node">4</div>
            <div class="timeline-node">5</div>
        </div>
        """, unsafe_allow_html=True)
        
        # Selector interactivo para ver el detalle de cada paso
        paso = st.radio("Detalle del Milestone:", ["1. Diagnóstico", "2. Políticas", "3. Implementación", "4. Auditoría Interna", "5. Certificación"], horizontal=True)
        
        if "1" in paso: st.info("Paso 1: Diagnóstico inicial de requerimientos legales y operativos en la planta.")
        elif "2" in paso: st.info("Paso 2: Creación de manuales, matriz de riesgos y política corporativa.")
        elif "3" in paso: st.info("Paso 3: Entrenamiento al personal y ejecución de nuevos procesos.")
        elif "4" in paso: st.info("Paso 4: Revisión interna para encontrar no conformidades antes de la auditoría oficial.")
        elif "5" in paso: st.info("Paso 5: Visita del organismo certificador y emisión del certificado.")
        
        st.markdown('</div>', unsafe_allow_html=True)

    # Cuadrantes Inferiores
    col3, col4 = st.columns(2)
    
    # Cuadrante 3: Ventajas ADICOM vs Clientes
    with col3:
        # Se construye el HTML de las ventajas asegurando usar unsafe_allow_html=True
        data = datos_certificacion.get(cert_sel, datos_certificacion["ISO 14001 (Ambiental)"])
        
        html_ventajas = '<div class="quadrant-card"><h3 style="color: #6baf84;">Ventajas Competitivas</h3><div style="display: flex; gap: 20px;">'
        
        # Columna ADICOM
        html_ventajas += '<div style="flex: 1;"><h4>🏢 Para ADICOM</h4>'
        for titulo, desc in data["ventajas_adicom"]:
            html_ventajas += f'<span class="badge-adicom">{titulo}</span><p style="font-size:0.9rem; color:#4b5563;">{desc}</p>'
        html_ventajas += '</div>'
        
        # Columna Clientes
        html_ventajas += '<div style="flex: 1;"><h4>🤝 Para CLIENTES</h4>'
        for titulo, desc in data["ventajas_clientes"]:
            html_ventajas += f'<span class="badge-client">{titulo}</span><p style="font-size:0.9rem; color:#4b5563;">{desc}</p>'
        html_ventajas += '</div>'
        
        html_ventajas += '</div></div>'
        st.markdown(html_ventajas, unsafe_allow_html=True)

    # Cuadrante 4: KPIs Financieros y Gráfica
    with col4:
        st.markdown('<div class="quadrant-card">', unsafe_allow_html=True)
        st.markdown('<h3 style="color: #6baf84;">Financial KPIs</h3>', unsafe_allow_html=True)
        
        kpis = datos_certificacion.get(cert_sel, datos_certificacion["ISO 14001 (Ambiental)"])["kpis"]
        kc1, kc2, kc3 = st.columns(3)
        kc1.metric("Inv. Inicial", kpis["Inv Inicial"])
        kc2.metric("ROI Esperado", kpis["ROI Esperado"])
        kc3.metric("Costo Mensual", kpis["Costo Mensual"])
        
        # Gráfica Plotly limpia y visible
        fig = go.Figure()
        fig.add_trace(go.Bar(x=['M1', 'M2', 'M3', 'M4', 'M5'], y=[50, 45, 30, 20, 15], name='Costo', marker_color='#94a3b8'))
        fig.add_trace(go.Scatter(x=['M1', 'M2', 'M3', 'M4', 'M5'], y=[10, 15, 30, 60, 85], name='Ahorro/Proxys (%)', mode='lines+markers', line=dict(color='#6baf84', width=3)))
        
        fig.update_layout(
            height=250, 
            margin=dict(l=0, r=0, t=30, b=0),
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
        )
        st.plotly_chart(fig, use_container_width=True)
        st.markdown('</div>', unsafe_allow_html=True)

elif menu_opcion == "Tabla Interactiva / Checklist global":
    st.title("📋 Tabla Interactiva y Documentos por Certificado")
    
    st.write("Aquí puedes marcar los documentos y requisitos que ya han sido cumplidos. **Los datos se guardan al hacer clic**.")
    
    col_docs, col_tabla = st.columns([1, 2])
    
    with col_docs:
        st.subheader("Documentos Clave")
        with st.expander("📄 ISO 14001", expanded=True):
            st.checkbox("Política ambiental y alcance del SGA", key="d1")
            st.checkbox("Matriz de aspectos e impactos ambientales", key="d2")
            st.checkbox("Objetivos ambientales y plan de acción", key="d3")
            st.checkbox("Plan de respuesta ante emergencias", key="d4")
            
        with st.expander("📄 ISO 45001"):
            st.checkbox("Política de SST y alcance", key="d5")
            st.checkbox("Matriz de peligros IPERC", key="d6")
            
    with col_tabla:
        st.subheader("Matriz de Cumplimiento Cruzado")
        # Creamos un dataframe interactivo (Streamlit Data Editor)
        df_matriz = pd.DataFrame({
            "Requisito": ["Control Documental", "Auditoría Interna", "Revisión por la Dirección", "Acciones Correctivas"],
            "ISO 9001": [True, True, False, True],
            "ISO 14001": [False, True, False, False],
            "ISO 45001": [False, False, False, False]
        })
        st.data_editor(df_matriz, use_container_width=True, hide_index=True)
