# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROfKHxt0mp7pg_hb2LhEsREzL8TW86Wi
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import sqlite3
import time

# ==========================================
# 1. CONFIGURACIÓN DE LA PÁGINA Y ESTILO
# ==========================================
st.set_page_config(
    page_title="ADICOM | Certifications Dashboard",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# URLs base de Google Sheets (Publicadas en CSV)
URL_KPIS_BASE = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQklg9IQYomXAn3t9xCsQu7zDScqlO38Yrl9rNXdscrdiao7wU1u3kyWJa7IPUR8g/pub?gid=1096975805&single=true&output=csv"
URL_ROADMAP_BASE = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQklg9IQYomXAn3t9xCsQu7zDScqlO38Yrl9rNXdscrdiao7wU1u3kyWJa7IPUR8g/pub?gid=2082257667&single=true&output=csv"

# Inyección de estilos CSS Modernos (SaaS Dashboard Style)
st.markdown("""
    <style>
    /* Fondo principal y tipografía */
    .stApp {
        background-color: #f0f4f8;
        font-family: 'Inter', 'Segoe UI', sans-serif;
    }
    
    /* Headers de colores */
    h1, h2, h3 {
        color: #102a43 !important;
        font-weight: 700 !important;
    }
    
    /* Tarjetas principales (Los 4 Cuadrantes) */
    .quadrant-card {
        background-color: #ffffff;
        border-radius: 16px;
        padding: 24px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
        border-top: 4px solid #334e68;
        height: 100%;
        margin-bottom: 20px;
    }
    
    /* Variaciones de color para el borde superior de los cuadrantes */
    .card-info { border-top-color: #2cb1bc; }
    .card-roadmap { border-top-color: #f59f00; }
    .card-advantages { border-top-color: #82c91e; }
    .card-kpis { border-top-color: #e03131; }
    
    /* Títulos de sección */
    .section-title {
        color: #334e68;
        text-transform: uppercase;
        font-size: 0.9rem;
        letter-spacing: 1.5px;
        margin-bottom: 15px;
        border-bottom: 2px solid #f0f4f8;
        padding-bottom: 8px;
        font-weight: bold;
    }

    /* Badges / Etiquetas (Arregladas) */
    .custom-badge-adicom { 
        background-color: #e6fcfa; 
        color: #0c8599; 
        padding: 4px 10px; 
        border-radius: 12px; 
        font-size: 0.8rem; 
        font-weight: bold; 
        margin-bottom: 5px; 
        display: inline-block;
    }
    .custom-badge-client { 
        background-color: #f3f0ff; 
        color: #6741d9; 
        padding: 4px 10px; 
        border-radius: 12px; 
        font-size: 0.8rem; 
        font-weight: bold; 
        margin-bottom: 5px; 
        display: inline-block;
    }
    
    /* Checkbox personalizado */
    .stCheckbox label p { font-size: 15px !important; color: #334e68 !important; font-weight: 500;}
    
    /* Timeline Visual mejorado (Ocultando los botones de radio estándar de Streamlit para hacerlos parecer nodos) */
    div.row-widget.stRadio > div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        position: relative;
        width: 100%;
        padding: 10px 0;
    }
    /* Línea conectora del timeline */
    div.row-widget.stRadio > div::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        right: 0;
        height: 4px;
        background-color: #d9e2ec;
        z-index: 0;
        transform: translateY(-50%);
    }
    /* Estilo de los "nodos" (opciones del radio) */
    div.row-widget.stRadio > div > label {
        position: relative;
        z-index: 1;
        background-color: #ffffff;
        padding: 5px 15px;
        border-radius: 20px;
        border: 2px solid #d9e2ec;
        margin-right: 10px;
        transition: all 0.3s ease;
    }
    div.row-widget.stRadio > div > label:hover {
        border-color: #f59f00;
        background-color: #fff9db;
    }
    /* Estilo del nodo seleccionado (la bolita de Streamlit se encarga, pero mejoramos el contenedor) */
    div.row-widget.stRadio > div > label[data-baseweb="radio"] {
        /* Puedes añadir más estilos si inspeccionas el DOM exacto, pero Streamlit maneja el color principal vía theming general */
    }

    /* Ajuste de métricas */
    [data-testid="stMetricValue"] { font-size: 1.8rem !important; color: #102a43; }
    [data-testid="stMetricLabel"] { font-size: 0.9rem !important; color: #627d98; }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. BASE DE DATOS LOCAL (PERSISTENCIA DE CHECKLIST)
# ==========================================
conn = sqlite3.connect('adicom_roadmap_v2.db', check_same_thread=False)
c = conn.cursor()
c.execute('CREATE TABLE IF NOT EXISTS checklist_v2 (task_id TEXT PRIMARY KEY, cert TEXT, status INTEGER)')
conn.commit()

def get_task_status(task_id, default_val=False):
    c.execute("SELECT status FROM checklist_v2 WHERE task_id=?", (task_id,))
    res = c.fetchone()
    return bool(res[0]) if res else default_val

def set_task_status(task_id, cert, status):
    new_status = 1 if status else 0
    c.execute("REPLACE INTO checklist_v2 (task_id, cert, status) VALUES (?, ?, ?)", (task_id, cert, new_status))
    conn.commit()

def update_task_callback(task_id, cert):
    val = st.session_state[task_id]
    set_task_status(task_id, cert, val)

# ==========================================
# 3. DATOS Y GOOGLE SHEETS
# ==========================================
@st.cache_data(ttl=5) 
def load_data_from_google_sheets(url_base):
    try:
        timestamp_url = f"{url_base}&_nocache={int(time.time())}"
        df = pd.read_csv(timestamp_url)
        df.columns = df.columns.str.strip()
        return df
    except Exception as e:
        return None

df_kpis = load_data_from_google_sheets(URL_KPIS_BASE)
df_roadmap = load_data_from_google_sheets(URL_ROADMAP_BASE)

data_kpis_board = pd.DataFrame({
    'Concepto': ['Inv. Inicial', 'ROI Esperado', 'Costo Operativo', 'Ahorro Proyectado'],
    'ISO_14001': [12000, 35, 2500, 18500],
    'ISO_45001': [15000, 28, 3000, 14200]
})

data_trends = pd.DataFrame({
    'Mes': ['M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    'Ahorro Generado': [10, 15, 25, 40, 55, 75],
    'Costo Implementación': [50, 45, 30, 20, 15, 10]
})

ROADMAP_DATA = {
    "ISO 14001": {
        "1. Diagnóstico": ["Mapeo de Procesos", "Análisis GAP Medioambiental", "Definición Política ISO 14001"],
        "2. Evaluación": ["Matriz de Impactos Ambientales", "Registro Requisitos Legales", "KPIs Ambientales"],
        "3. Operación": ["Capacitación de Personal", "Control de Residuos", "Simulacros de Emergencia"],
        "4. Certificación": ["Auditoría Interna", "Acciones Correctivas", "Auditoría Externa (Certificadora)"]
    },
    "ISO 45001": {
        "1. Diagnóstico": ["Inspección de Instalaciones", "Análisis GAP Seguridad", "Definición Política SST"],
        "2. Evaluación": ["Matriz IPERC (Riesgos)", "Exámenes Médicos Ocupacionales", "Requisitos Legales STPS"],
        "3. Operación": ["Entrega EPP", "Capacitación Brigadas", "Señalización"],
        "4. Certificación": ["Auditoría Interna SST", "Revisión por la Dirección", "Auditoría Externa"]
    }
}

# ==========================================
# 4. BARRA LATERAL
# ==========================================
with st.sidebar:
    st.markdown("""
        <div style='text-align: center; padding: 10px 0 20px 0;'>
            <h1 style='color: #102a43; font-size: 28px; margin-bottom: 0;'>ADICOM</h1>
            <p style='color: #2cb1bc; font-weight: 600; letter-spacing: 2px; font-size: 12px; margin-top: 0;'>CERTIFICATION DASHBOARD</p>
        </div>
    """, unsafe_allow_html=True)
    
    menu = st.radio(
        "SELECCIONA VISTA:",
        ["📘 ISO 14001", "📙 ISO 45001", "✅ Checklist Global", "🔄 Datos"]
    )
    
    st.markdown("---")
    st.markdown("**Progreso Global:**")
    c.execute("SELECT COUNT(*) FROM checklist_v2")
    totales = c.fetchone()[0] or 1
    c.execute("SELECT COUNT(*) FROM checklist_v2 WHERE status=1")
    hechas = c.fetchone()[0] or 0
    progreso = int((hechas / max(totales, 1)) * 100)
    st.progress(progreso / 100.0)
    st.caption(f"{hechas} tareas de {totales} ({progreso}%)")

# ==========================================
# 5. RENDERIZADO DE LAS VISTAS
# ==========================================

if menu in ["📘 ISO 14001", "📙 ISO 45001"]:
    cert_name = "ISO 14001" if "14001" in menu else "ISO 45001"
    
    st.markdown(f"<h1 style='text-align: center; font-size: 2.5rem; margin-bottom: 20px; border-bottom: 4px solid #102a43; padding-bottom: 10px;'>{cert_name} Dashboard</h1>", unsafe_allow_html=True)
    
    # --- FILA 1 ---
    col1, col2 = st.columns([1, 1.2])
    
    with col1:
        st.markdown(f"""
        <div class="quadrant-card card-info">
            <div class="section-title">¿Qué es?</div>
            <p style='color: #486581; font-size: 1rem; line-height: 1.5;'>
                {'Norma internacional para <b>Sistemas de Gestión Ambiental (SGA)</b>. Ayuda a controlar impactos ambientales, reducir residuos y cumplir con la legislación vigente, mejorando la imagen corporativa.' if cert_name == 'ISO 14001' else 'Norma internacional para <b>Sistemas de Gestión de Seguridad y Salud en el Trabajo (SST)</b>. Previene lesiones, enfermedades laborales y asegura un entorno de trabajo seguro.'}
            </p>
            <br>
            <div class="section-title">Documentos Clave</div>
            <ul style='color: #486581; font-size: 0.95rem;'>
                <li>Manual del Sistema de Gestión</li>
                <li>Matriz de {'Aspectos e Impactos Ambientales' if cert_name == 'ISO 14001' else 'Peligros y Riesgos (IPERC)'}</li>
                <li>Procedimientos Operativos Estandarizados</li>
                <li>Registros de Auditoría Interna</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        # Aquí estilizamos el Roadmap para que parezca un timeline con bolitas
        st.markdown("""<div class="quadrant-card card-roadmap">
            <div class="section-title">Roadmap Interactivo</div>
        """, unsafe_allow_html=True)
        
        fases = list(ROADMAP_DATA[cert_name].keys())
        
        # El radio button se verá como timeline gracias al CSS inyectado arriba
        selected_phase = st.radio(
            "Progreso de Implementación", 
            fases, 
            horizontal=True,
            label_visibility="collapsed" # Ocultamos el label por defecto para que sea más limpio
        )
        
        st.markdown(f"<h4 style='color: #f59f00; margin-top: 20px;'>Checklist Fase: {selected_phase}</h4>", unsafe_allow_html=True)
        
        # Checkboxes
        for task in ROADMAP_DATA[cert_name][selected_phase]:
            task_id = f"{cert_name}_{selected_phase}_{task}".replace(" ", "_")
            current_val = get_task_status(task_id)
            
            st.checkbox(
                task, 
                value=current_val, 
                key=task_id, 
                on_change=update_task_callback, 
                args=(task_id, cert_name)
            )
            
        st.markdown("</div>", unsafe_allow_html=True)

    # --- FILA 2 ---
    col3, col4 = st.columns([1, 1.2])
    
    with col3:
        # ARREGLADO: El error del renderizado negro fue por mezclar HTML y Markdown incorrectamente.
        # Ahora usamos st.container y divisiones nativas de Streamlit en lugar de un gran bloque HTML,
        # O nos aseguramos de que el HTML sea 100% puro y no lo rompa el parser de Markdown.
        
        # Usaré HTML limpio y cerrado correctamente para asegurar que no se rompa el estilo.
        html_advantages = """
        <div class="quadrant-card card-advantages" style="background-color: white;">
            <div class="section-title">Ventajas Competitivas</div>
            <div style='display: flex; justify-content: space-between; gap: 20px;'>
                
                <!-- Columna Adicom -->
                <div style='flex: 1; border-right: 1px solid #d9e2ec; padding-right: 15px;'>
                    <h4 style='color: #0c8599; margin-bottom: 15px;'>Para ADICOM</h4>
                    
                    <div style="margin-bottom: 15px;">
                        <span class='custom-badge-adicom'>Reducción de Costos</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Optimización de recursos y menos multas.</p>
                    </div>
                    
                    <div style="margin-bottom: 15px;">
                        <span class='custom-badge-adicom'>Diferenciador Mercado</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Puntaje extra en licitaciones.</p>
                    </div>
                    
                    <div>
                        <span class='custom-badge-adicom'>Operación Ágil</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Procesos estandarizados y medibles.</p>
                    </div>
                </div>
                
                <!-- Columna Clientes -->
                <div style='flex: 1; padding-left: 5px;'>
                    <h4 style='color: #6741d9; margin-bottom: 15px;'>Para CLIENTES</h4>
                    
                    <div style="margin-bottom: 15px;">
                        <span class='custom-badge-client'>Confianza / Trust</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Garantía de calidad corporativa.</p>
                    </div>
                    
                    <div style="margin-bottom: 15px;">
                        <span class='custom-badge-client'>Cadena Segura</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Cumplimiento normativo heredado.</p>
                    </div>
                    
                    <div>
                        <span class='custom-badge-client'>Continuidad Negocio</span>
                        <p style='font-size: 0.9rem; color: #486581; margin: 0;'>Menor riesgo de paros.</p>
                    </div>
                </div>
                
            </div>
        </div>
        """
        st.markdown(html_advantages, unsafe_allow_html=True)


    with col4:
        # ARREGLADO: Gráfico y tarjeta KPIs limpios sin sobreposiciones extrañas
        st.markdown("""<div class="quadrant-card card-kpis" style="background-color: white;">
            <div class="section-title">Impacto Financiero (KPIs)</div>
        """, unsafe_allow_html=True)
        
        cert_col = 'ISO_14001' if cert_name == 'ISO 14001' else 'ISO_45001'
        inv = data_kpis_board.loc[data_kpis_board['Concepto'] == 'Inv. Inicial', cert_col].values[0]
        roi = data_kpis_board.loc[data_kpis_board['Concepto'] == 'ROI Esperado', cert_col].values[0]
        costo = data_kpis_board.loc[data_kpis_board['Concepto'] == 'Costo Operativo', cert_col].values[0]
        
        # Métricas alineadas
        mc1, mc2, mc3 = st.columns(3)
        mc1.metric("Inv. Inicial", f"${inv:,}")
        mc2.metric("ROI Esperado", f"{roi}%")
        mc3.metric("Costo", f"${costo:,}")
        
        # Gráfica
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=data_trends['Mes'], y=data_trends['Costo Implementación'], 
            name='Costo', marker_color='#334e68'
        ))
        fig.add_trace(go.Scatter(
            x=data_trends['Mes'], y=data_trends['Ahorro Generado'], 
            name='Beneficios', mode='lines+markers',
            line=dict(color='#2cb1bc', width=3), marker=dict(size=8)
        ))
        
        fig.update_layout(
            title="Evolución (Costos vs Beneficios)",
            title_font_size=14,
            template="plotly_white",
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            margin=dict(l=0, r=0, t=30, b=0),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            height=200 # Ajuste de altura para que no desborde la tarjeta
        )
        st.plotly_chart(fig, use_container_width=True)
        
        st.markdown("</div>", unsafe_allow_html=True)

# ------------------------------------------
# VISTA: TABLA Y CHECKLIST
# ------------------------------------------
elif menu == "✅ Checklist Global":
    st.markdown("<h1>Resumen Ejecutivo & Control</h1>", unsafe_allow_html=True)
    
    t1, t2 = st.tabs(["📋 Progreso Detallado", "🧮 Matriz de Integración"])
    
    with t1:
        st.markdown("### Control de Tareas por Fase")
        colA, colB = st.columns(2)
        
        for i, (cert, fases) in enumerate(ROADMAP_DATA.items()):
            target_col = colA if i == 0 else colB
            with target_col:
                st.markdown(f"**{cert}**")
                for fase, tareas in fases.items():
                    with st.expander(fase, expanded=False):
                        for task in tareas:
                            task_id = f"{cert}_{fase}_{task}".replace(" ", "_")
                            current_val = get_task_status(task_id)
                            st.checkbox(task, value=current_val, key=f"global_{task_id}", 
                                        on_change=update_task_callback, args=(f"global_{task_id}", cert))
                    
    with t2:
        st.markdown("### Integración de Sistemas (SGI)")
        st.info("Muestra qué requisitos pueden integrarse para evitar trabajo doble al buscar múltiples ISOs.")
        
        tabla_interactiva = pd.DataFrame({
            'Proceso Core': ['Control Documental', 'Auditorías Internas', 'Gestión de Riesgos', 'Política Ambiental', 'Política SST'],
            'ISO 14001': ['✅ Compartido', '✅ Compartido', '✅ Específico', '✅ Obligatorio', '❌ No Aplica'],
            'ISO 45001': ['✅ Compartido', '✅ Compartido', '✅ Específico', '❌ No Aplica', '✅ Obligatorio']
        })
        st.dataframe(tabla_interactiva, use_container_width=True, hide_index=True)

# ------------------------------------------
# VISTA: DATOS
# ------------------------------------------
elif menu == "🔄 Datos":
    st.markdown("<h1>Conexión de Datos</h1>", unsafe_allow_html=True)
    
    if st.button("🔄 Refrescar datos desde Google Sheets", type="primary"):
        st.cache_data.clear()
        st.rerun()
        
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("### Data KPIs")
        if df_kpis is not None:
            st.dataframe(df_kpis)
        else:
            st.error("No se pudo conectar. Revisa la URL.")
            
    with col2:
        st.markdown("### Data Roadmap")
        if df_roadmap is not None:
            st.dataframe(df_roadmap)
        else:
            st.error("No se pudo conectar. Revisa la URL.")
